# Generated by Django 4.2.6 on 2023-11-01 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=48)),
                ('cedula', models.IntegerField()),
                ('correo', models.CharField(max_length=45)),
                ('usuario', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('contraseña', models.CharField(max_length=45)),
                ('huella', models.CharField(max_length=200)),
            ],
        ),
    ]
