# Generated by Django 4.2.6 on 2023-11-04 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_adminuser_normaluser_delete_usuadm_and_more'),
        ('curso', '0002_alter_clase_profesor_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profesor',
        ),
    ]
