# Generated by Django 4.2.6 on 2023-11-04 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_delete_profesor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='normaluser',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='normaluser',
            name='cedula',
        ),
        migrations.RemoveField(
            model_name='normaluser',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='normaluser',
            name='id',
        ),
        migrations.RemoveField(
            model_name='normaluser',
            name='nombre',
        ),
        migrations.AddField(
            model_name='normaluser',
            name='user',
            field=models.CharField(default=1, max_length=50, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
