# Generated by Django 4.2.6 on 2023-11-04 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_remove_normaluser_apellido_remove_normaluser_cedula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normaluser',
            name='user',
            field=models.CharField(default=None, max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
