# Generated by Django 4.2.6 on 2023-11-04 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_alter_normaluser_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminuser',
            options={'verbose_name': 'Usuario administrador', 'verbose_name_plural': 'Usuarios administradores'},
        ),
        migrations.AlterModelOptions(
            name='normaluser',
            options={'verbose_name': 'Usuario Normal', 'verbose_name_plural': 'Usuarios Normales'},
        ),
    ]
