# Generated by Django 4.2.6 on 2023-11-04 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0010_delete_normaluser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='huella',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
