# Generated by Django 4.2.6 on 2023-11-04 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0012_remove_newuser_user_alter_newuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='admin_check',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
