# Generated by Django 4.2.6 on 2023-11-04 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0013_newuser_admin_check'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='newuser',
            managers=[
            ],
        ),
    ]
