# Generated by Django 4.2.6 on 2023-11-04 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0015_alter_newuser_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='admin_check',
            field=models.BooleanField(default=False),
        ),
    ]
