# Generated by Django 4.2.6 on 2023-11-04 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_adminuser_normaluser_delete_usuadm_and_more'),
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='profesor_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuario.normaluser'),
        ),
    ]
