# Generated by Django 4.2.6 on 2023-11-04 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0009_newuser_remove_normaluser_groups_and_more'),
        ('curso', '0002_alter_clase_profesor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='profesor_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuario.newuser'),
        ),
    ]
